appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: Rm/iY7F9lug6BIjTjQMYMyEfAzna0CPvaK+2Emja7udFU6g8A8TltsFH3B7MLMdgxiQ+YNaxUlgPhlCav0Pr0U00YDBbPb6PMgyP0I0st/G7++OJ0wwGXBmz+u/hyDqVi7jUPv31zYh6FHz+0eozuuytkK2FolTXdZeybEScafd0MNdc6jYbph1enxhpQTOm+5p0qaSmGcDTpbEl42X11UuqrjqYluelzuT/Eyk/LU9oKJwWomWjjugbw+cxCvmTGIvrb3DLMni+mdFaI2Vd0mPDQGhQpBvK5yXsrPPSsk8pKB6szwMLImVsUkGizR0YJAAm8WN30AE2JRa/pJEyTHJlHNrwghoBTNycaoNTzopGP3TJAd7MRqLVLBXWBicMEj4HO+e8QbaiFNnL9hyKEUjDdgIlwspQxTO9eAOq7SUA3WncANgfrQSJv3/U67NzQfinwvtrByNjcbeQqOOon0kBNkGsY7pccnkK8pcCHweHzh9nXySBKnW1WnjEph1VWsdgaMSUlZehsG+afEi1CuSvBSowreyfV5vHOZ54XdC04GqtAb8y8qXbNXmCkyPlFhcCUcoOihxhkyC1wbKMtNdXDErflzU1C/XgnCTdNP5NKyRhEDm8oCO/OY4X9iuu1xAY0/fY/P2ZkPdbuRF5ya2mTgttOV1NY78v9LP/ay8=
