travis:
  secure:
    BINSTAR_TOKEN: eBpg3ULUhjx8EEYctDsjtKCXDHtl01Tnb50+AY3SRrszQfw/WfJS6yjIq7FRBZDtN2DyuE/CIH8B1wQd/o53SFAmOH/wzmMUEju2rkyeqU2EgWsMuleAo28QjVhrHgsVrR2IZddwGEpfMBmHjBWpqhaSCuWRTBuLvfnH2vcZo9QAYd5QE+WpOdr222BdwAbfDwv6gpruMDCD9gJN2I0163myFL2gdyGGyZEIPUrLIu4rAaMrMIg6xlOIEWru7O907aZPz0KVMg7Ii7TKAi9qq0ylHdOShQNsXKVju9/3PeHlqmZDRY8znSB71Yy2RkFtF1sO5mlO9S8DHEn9Q/bYFfadWyVlmRA26Dvq68tQmEpApM//Owo4g8o2ngPlu45g4m65zdMBhrghkmXeNVBl5rPe+kgwp5rRNYZg5BwNVhIf/PJsmYAP6qlHPqTIPHRbWl+91KKotuKJPjxxPWPXdtbYmW1u8lHiOk2d8neqmCIBLtyaoMlVGtCt1s5M2rnGJBGAgzuUtcrlgayUSmWD2ppxWeNpC1otCBL3pdwqRezOFp3DqVp46mflH1Dqw7WFQA9hwl8etOW7txRY6xwSXl1eHNZRNtca4UMb3X1o7xC6Xq+/VJptZ2L9a8w9LSQ/H98iK35t4Iy8hZNXJNM39AuQ9KpMJwps7YBQiS7PjbQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
